# RadioML 2018 Dataset Exploration and Analysis

**Project:** Automatic Modulation Classification using Deep Learning

**Dataset:** RadioML 2018.01A

**Objective:**
To understand the structure, organization, and statistical properties of the RadioML 2018 dataset before performing preprocessing and model development.

## Relationship Between `X`, `Y`, and `Z`

The RadioML 2018 dataset stores the IQ waveform, modulation label, and Signal-to-Noise Ratio (SNR) in three separate datasets. These datasets are synchronized using a common sample index. Therefore, the *i-th* entry of `X`, `Y`, and `Z` together represent one complete radio signal instance.

For example:

| Sample Index | IQ Signal (`X`) | Modulation Label (`Y`) | SNR (`Z`) |
|:------------:|:----------------|:-----------------------|:---------:|
| **0** | `X[0]` → IQ waveform | `Y[0]` → Modulation type | `Z[0]` → SNR |
| **1** | `X[1]` → IQ waveform | `Y[1]` → Modulation type | `Z[1]` → SNR |
| **2** | `X[2]` → IQ waveform | `Y[2]` → Modulation type | `Z[2]` → SNR |
| ⋮ | ⋮ | ⋮ | ⋮ |
| **N** | `X[N]` → IQ waveform | `Y[N]` → Modulation type | `Z[N]` → SNR |

### Key Concept

For every sample index **i**:

- `X[i]` contains the IQ signal samples.
- `Y[i]` contains the corresponding modulation class.
- `Z[i]` contains the corresponding Signal-to-Noise Ratio (SNR).

These three entries always refer to the **same transmitted signal**.

For example, if `i = 150`:

```text
X[150]  → IQ waveform
Y[150]  → QPSK
Z[150]  → 10 dB
```

This means that the IQ waveform stored in `X[150]` was generated using **QPSK modulation** and corrupted by noise corresponding to an **SNR of 10 dB**.

```text
                    Sample Index = i
                           │
        ┌──────────────────┼──────────────────┐
        │                  │                  │
        ▼                  ▼                  ▼
      X[i]              Y[i]               Z[i]
 IQ Waveform      Modulation Label      SNR Value
        │                  │                  │
        └──────────────────┴──────────────────┘
                           │
                           ▼
                One Radio Signal Instance
```

In [34]:
import h5py
import numpy as np


Loading the Datasets

In [3]:
filename="E:\\AMC\\datasets\\RadioMl2018\\GOLD_XYZ_OSC.0001_1024.hdf5"
f = h5py.File(filename, 'r')
print("Datasets loaded successfully!")

Datasets loaded successfully!


Extracting the Keys in from the Datasets

In [4]:
print("Root Keys:\n")

for key in f.keys():
    print(key)

Root Keys:

X
Y
Z


In [ ]:
for key in f.keys():
    print("-"*50)
    print(f"Key: {key}")
    print(f'Shape: {f[key].shape}')
    print(f'Data type: {f[key].dtype}')
    

--------------------------------------------------
Key: X
Shape: (2555904, 1024, 2)
Data type: float32

--------------------------------------------------
Key: Y
Shape: (2555904, 24)
Data type: int64

--------------------------------------------------
Key: Z
Shape: (2555904, 1)
Data type: int64



In [15]:
sample=f['X'][-10:] #printing last 10 samples

sample

array([[[ 2.64472723e-01, -3.36526126e-01],
        [ 8.88159126e-02, -3.21319908e-01],
        [-7.69267753e-02, -3.40281636e-01],
        ...,
        [ 9.35314775e-01,  1.01010525e+00],
        [ 1.00654304e+00,  8.71628106e-01],
        [ 1.06913996e+00,  6.93452120e-01]],

       [[-1.21566653e+00,  5.18357813e-01],
        [-1.33779216e+00,  3.54542315e-01],
        [-1.42758262e+00,  1.98224679e-01],
        ...,
        [-4.28200036e-01,  7.89410323e-02],
        [-2.61783600e-01,  1.10993467e-01],
        [-1.06698506e-01,  2.03049257e-01]],

       [[-9.45832431e-01, -6.72811985e-01],
        [-8.84582698e-01, -6.71573400e-01],
        [-8.13542545e-01, -6.37165546e-01],
        ...,
        [-1.42656386e-01, -9.84321833e-01],
        [-2.23283648e-01, -1.16084540e+00],
        [-3.26148570e-01, -1.24667954e+00]],

       ...,

       [[ 8.14449430e-01,  5.54006159e-01],
        [ 6.56121612e-01,  4.91486609e-01],
        [ 4.43010390e-01,  3.75899732e-01],
        ...,
     

In [18]:
X=f['X']

print(f"Shape of X: {X[0].shape}")

Shape of X: (1024, 2)


Exploring Y

In [21]:
y=f["Y"]

In [33]:
first_sample=y[0][1]

first_sample

np.int64(0)

In [22]:
print(type(y))
print(y.shape)
print(y.dtype)


<class 'h5py._hl.dataset.Dataset'>
(2555904, 24)
int64


In [25]:
print(y[10067:10077]) #printing 10 samples of y

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [30]:
print(y.shape[0])
print(y.shape[1])

2555904
24


In [35]:
print(np.sum(y[0]))

1


In [36]:
print(np.unique(y)) #printing unique values of y

[0 1]


In [ ]:
#counting unique labels in y
labels=np.argmax(y[:],axis=1)

unique=np.unique(labels)

print(unique)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
#Count samples in each class 
classes, counts = np.unique(labels, return_counts=True)

for c,n in zip(classes,counts):
    print(f"Class {c:2d}: {n}")

Class  0: 106496
Class  1: 106496
Class  2: 106496
Class  3: 106496
Class  4: 106496
Class  5: 106496
Class  6: 106496
Class  7: 106496
Class  8: 106496
Class  9: 106496
Class 10: 106496
Class 11: 106496
Class 12: 106496
Class 13: 106496
Class 14: 106496
Class 15: 106496
Class 16: 106496
Class 17: 106496
Class 18: 106496
Class 19: 106496
Class 20: 106496
Class 21: 106496
Class 22: 106496
Class 23: 106496


Exploring Z key

In [39]:
Z = f["Z"]

print(type(Z))
print(Z.shape)
print(Z.dtype)

<class 'h5py._hl.dataset.Dataset'>
(2555904, 1)
int64


In [40]:
print(Z[:10])

[[-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]]


In [41]:
#minimum value of Z
print(np.min(Z))

-20


In [42]:
#maximum value of Z
print(np.max(Z))

30


In [43]:
#unique snr

snr=np.unique(Z)

snr

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,
         6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30])

In [44]:
#counting sample at each SNR
snr_values, counts = np.unique(Z, return_counts=True)

for s,c in zip(snr_values,counts):
    print(f"{s:>3} dB : {c}")

-20 dB : 98304
-18 dB : 98304
-16 dB : 98304
-14 dB : 98304
-12 dB : 98304
-10 dB : 98304
 -8 dB : 98304
 -6 dB : 98304
 -4 dB : 98304
 -2 dB : 98304
  0 dB : 98304
  2 dB : 98304
  4 dB : 98304
  6 dB : 98304
  8 dB : 98304
 10 dB : 98304
 12 dB : 98304
 14 dB : 98304
 16 dB : 98304
 18 dB : 98304
 20 dB : 98304
 22 dB : 98304
 24 dB : 98304
 26 dB : 98304
 28 dB : 98304
 30 dB : 98304


Checking Datasets Attributes


In [16]:
for key in f.keys():
    print("="*60)
    print(key)

    attrs = f[key].attrs

    if len(attrs)==0:
        print("No attributes found.")

    else:
        for attr in attrs:
            print(attr, ":", attrs[attr])

X
No attributes found.
Y
No attributes found.
Z
No attributes found.


**Relationship Between X, Y and Z**

Dataset Index
      │
      ▼
+------------------------------------------------------+
| Sample 0                                             |
|                                                      |
| X[0] → IQ waveform                                   |
| Y[0] → Modulation type                               |
| Z[0] → Signal-to-Noise Ratio                         |
+------------------------------------------------------+

+------------------------------------------------------+
| Sample 1                                             |
|                                                      |
| X[1] → IQ waveform                                   |
| Y[1] → Modulation type                               |
| Z[1] → Signal-to-Noise Ratio                         |
+------------------------------------------------------+

                ⋮

+------------------------------------------------------+
| Sample N                                             |
|                                                      |
| X[N] → IQ waveform                                   |
| Y[N] → Modulation type                               |
| Z[N] → Signal-to-Noise Ratio                         |
+------------------------------------------------------+

In [46]:
idx = 0

print("Signal Shape :", X[idx].shape)
print("Label Index  :", np.argmax(y[idx]))
print("SNR          :", Z[idx])

Signal Shape : (1024, 2)
Label Index  : 0
SNR          : [-20]


In [48]:
# repeating for a few more samples

indices = [0, 100, 1000, 5000]

for idx in indices:
    print(f"\nSample {idx}")
    print("Signal shape :", X[idx].shape)
    print("Class        :", np.argmax(y[idx]))
    print("SNR          :", Z[idx])


Sample 0
Signal shape : (1024, 2)
Class        : 0
SNR          : [-20]

Sample 100
Signal shape : (1024, 2)
Class        : 0
SNR          : [-20]

Sample 1000
Signal shape : (1024, 2)
Class        : 0
SNR          : [-20]

Sample 5000
Signal shape : (1024, 2)
Class        : 0
SNR          : [-18]
