# RadioML 2018 Dataset Exploration and Analysis

**Project:** Automatic Modulation Classification using Deep Learning

**Dataset:** RadioML 2018.01A

**Objective:**
To understand the structure, organization, and statistical properties of the RadioML 2018 dataset before performing preprocessing and model development.

## Relationship Between `X`, `Y`, and `Z`

The RadioML 2018 dataset stores the IQ waveform, modulation label, and Signal-to-Noise Ratio (SNR) in three separate datasets. These datasets are synchronized using a common sample index. Therefore, the *i-th* entry of `X`, `Y`, and `Z` together represent one complete radio signal instance.

For example:

| Sample Index | IQ Signal (`X`) | Modulation Label (`Y`) | SNR (`Z`) |
|:------------:|:----------------|:-----------------------|:---------:|
| **0** | `X[0]` → IQ waveform | `Y[0]` → Modulation type | `Z[0]` → SNR |
| **1** | `X[1]` → IQ waveform | `Y[1]` → Modulation type | `Z[1]` → SNR |
| **2** | `X[2]` → IQ waveform | `Y[2]` → Modulation type | `Z[2]` → SNR |
| ⋮ | ⋮ | ⋮ | ⋮ |
| **N** | `X[N]` → IQ waveform | `Y[N]` → Modulation type | `Z[N]` → SNR |

### Key Concept

For every sample index **i**:

- `X[i]` contains the IQ signal samples.
- `Y[i]` contains the corresponding modulation class.
- `Z[i]` contains the corresponding Signal-to-Noise Ratio (SNR).

These three entries always refer to the **same transmitted signal**.

For example, if `i = 150`:

```text
X[150]  → IQ waveform
Y[150]  → QPSK
Z[150]  → 10 dB
```

This means that the IQ waveform stored in `X[150]` was generated using **QPSK modulation** and corrupted by noise corresponding to an **SNR of 10 dB**.

```text
                    Sample Index = i
                           │
        ┌──────────────────┼──────────────────┐
        │                  │                  │
        ▼                  ▼                  ▼
      X[i]              Y[i]               Z[i]
 IQ Waveform      Modulation Label      SNR Value
        │                  │                  │
        └──────────────────┴──────────────────┘
                           │
                           ▼
                One Radio Signal Instance
```

In [37]:
import h5py
import numpy as np


Loading the Datasets

In [38]:
filename="E:\\AMC\\datasets\\RadioMl2018\\GOLD_XYZ_OSC.0001_1024.hdf5"
f = h5py.File(filename, 'r')
print("Datasets loaded successfully!")

Datasets loaded successfully!


Extracting the Keys in from the Datasets

In [39]:
print("Root Keys:\n")

for key in f.keys():
    print(key)

Root Keys:

X
Y
Z


In [40]:
for key in f.keys():
    print("-"*50)
    print(f"Key: {key}")
    print(f'Shape: {f[key].shape}')
    print(f'Data type: {f[key].dtype}')
    

--------------------------------------------------
Key: X
Shape: (2555904, 1024, 2)
Data type: float32
--------------------------------------------------
Key: Y
Shape: (2555904, 24)
Data type: int64
--------------------------------------------------
Key: Z
Shape: (2555904, 1)
Data type: int64


In [41]:
sample=f['X'][-10:] #printing last 10 samples

sample

array([[[ 2.64472723e-01, -3.36526126e-01],
        [ 8.88159126e-02, -3.21319908e-01],
        [-7.69267753e-02, -3.40281636e-01],
        ...,
        [ 9.35314775e-01,  1.01010525e+00],
        [ 1.00654304e+00,  8.71628106e-01],
        [ 1.06913996e+00,  6.93452120e-01]],

       [[-1.21566653e+00,  5.18357813e-01],
        [-1.33779216e+00,  3.54542315e-01],
        [-1.42758262e+00,  1.98224679e-01],
        ...,
        [-4.28200036e-01,  7.89410323e-02],
        [-2.61783600e-01,  1.10993467e-01],
        [-1.06698506e-01,  2.03049257e-01]],

       [[-9.45832431e-01, -6.72811985e-01],
        [-8.84582698e-01, -6.71573400e-01],
        [-8.13542545e-01, -6.37165546e-01],
        ...,
        [-1.42656386e-01, -9.84321833e-01],
        [-2.23283648e-01, -1.16084540e+00],
        [-3.26148570e-01, -1.24667954e+00]],

       ...,

       [[ 8.14449430e-01,  5.54006159e-01],
        [ 6.56121612e-01,  4.91486609e-01],
        [ 4.43010390e-01,  3.75899732e-01],
        ...,
     

In [42]:
X=f['X']

print(f"Shape of X: {X[0].shape}")

Shape of X: (1024, 2)


Exploring Y

In [43]:
Y=f["Y"]

In [44]:
first_sample=y[0][1]

first_sample

np.int64(0)

In [45]:
print(type(Y))
print(Y.shape)
print(Y.dtype)


<class 'h5py._hl.dataset.Dataset'>
(2555904, 24)
int64


In [46]:
print(Y[10067:10077]) #printing 10 samples of Y

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [47]:
print(Y.shape[0])
print(Y.shape[1])

2555904
24


In [48]:
print(np.sum(Y[0]))

1


In [49]:
print(np.unique(Y)) #printing unique values of Y

[0 1]


In [50]:
#counting unique labels in Y
labels=np.argmax(Y[:],axis=1)

unique=np.unique(labels)

print(unique)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [51]:
#Count samples in each class 
classes, counts = np.unique(labels, return_counts=True)

for c,n in zip(classes,counts):
    print(f"Class {c:2d}: {n}")

Class  0: 106496
Class  1: 106496
Class  2: 106496
Class  3: 106496
Class  4: 106496
Class  5: 106496
Class  6: 106496
Class  7: 106496
Class  8: 106496
Class  9: 106496
Class 10: 106496
Class 11: 106496
Class 12: 106496
Class 13: 106496
Class 14: 106496
Class 15: 106496
Class 16: 106496
Class 17: 106496
Class 18: 106496
Class 19: 106496
Class 20: 106496
Class 21: 106496
Class 22: 106496
Class 23: 106496


Exploring Z key

In [52]:
Z = f["Z"]

print(type(Z))
print(Z.shape)
print(Z.dtype)

<class 'h5py._hl.dataset.Dataset'>
(2555904, 1)
int64


In [53]:
print(Z[:10])

[[-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]
 [-20]]


In [54]:
#minimum value of Z
print(np.min(Z))

-20


In [55]:
#maximum value of Z
print(np.max(Z))

30


In [56]:
#unique snr

snr=np.unique(Z)

snr

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,
         6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30])

In [57]:
#counting sample at each SNR
snr_values, counts = np.unique(Z, return_counts=True)

for s,c in zip(snr_values,counts):
    print(f"{s:>3} dB : {c}")

-20 dB : 98304
-18 dB : 98304
-16 dB : 98304
-14 dB : 98304
-12 dB : 98304
-10 dB : 98304
 -8 dB : 98304
 -6 dB : 98304
 -4 dB : 98304
 -2 dB : 98304
  0 dB : 98304
  2 dB : 98304
  4 dB : 98304
  6 dB : 98304
  8 dB : 98304
 10 dB : 98304
 12 dB : 98304
 14 dB : 98304
 16 dB : 98304
 18 dB : 98304
 20 dB : 98304
 22 dB : 98304
 24 dB : 98304
 26 dB : 98304
 28 dB : 98304
 30 dB : 98304


Checking Datasets Attributes


In [58]:
for key in f.keys():
    print("="*60)
    print(key)

    attrs = f[key].attrs

    if len(attrs)==0:
        print("No attributes found.")

    else:
        for attr in attrs:
            print(attr, ":", attrs[attr])

X
No attributes found.
Y
No attributes found.
Z
No attributes found.


**Relationship Between X, Y and Z**

Dataset Index
      │
      ▼
+------------------------------------------------------+
| Sample 0                                             |
|                                                      |
| X[0] → IQ waveform                                   |
| Y[0] → Modulation type                               |
| Z[0] → Signal-to-Noise Ratio                         |
+------------------------------------------------------+

+------------------------------------------------------+
| Sample 1                                             |
|                                                      |
| X[1] → IQ waveform                                   |
| Y[1] → Modulation type                               |
| Z[1] → Signal-to-Noise Ratio                         |
+------------------------------------------------------+

                ⋮

+------------------------------------------------------+
| Sample N                                             |
|                                                      |
| X[N] → IQ waveform                                   |
| Y[N] → Modulation type                               |
| Z[N] → Signal-to-Noise Ratio                         |
+------------------------------------------------------+

In [59]:
idx = 0

print("Signal Shape :", X[idx].shape)
print("Label Index  :", np.argmax(Y[idx]))
print("SNR          :", Z[idx])

Signal Shape : (1024, 2)
Label Index  : 0
SNR          : [-20]


In [60]:
# repeating for a few more samples

indices = [0, 100, 1000, 5000]

for idx in indices:
    print(f"\nSample {idx}")
    print("Signal shape :", X[idx].shape)
    print("Class        :", np.argmax(Y[idx]))
    print("SNR          :", Z[idx])


Sample 0
Signal shape : (1024, 2)
Class        : 0
SNR          : [-20]

Sample 100
Signal shape : (1024, 2)
Class        : 0
SNR          : [-20]

Sample 1000
Signal shape : (1024, 2)
Class        : 0
SNR          : [-20]

Sample 5000
Signal shape : (1024, 2)
Class        : 0
SNR          : [-18]


## Decoding Modulation Labels

The RadioML 2018 dataset stores modulation labels using **one-hot encoding** instead of text.

For example:

| Modulation | One-Hot Encoding |
|------------|------------------|
| OOK | [1,0,0,...,0] |
| BPSK | [0,0,0,1,...,0] |
| QPSK | [0,0,0,0,1,...,0] |

The active element (value = 1) indicates the modulation class.

The corresponding class index is obtained using `numpy.argmax()`, and the modulation name is retrieved from `classes-fixed.json`.

In [61]:
import json

with open("E:\AMC\datasets\RadioMl2018\classes-fixed.json", "r") as f:
    classes = json.load(f)

print(type(classes))
print(classes)

<class 'list'>
['OOK', '4ASK', '8ASK', 'BPSK', 'QPSK', '8PSK', '16PSK', '32PSK', '16APSK', '32APSK', '64APSK', '128APSK', '16QAM', '32QAM', '64QAM', '128QAM', '256QAM', 'AM-SSB-WC', 'AM-SSB-SC', 'AM-DSB-WC', 'AM-DSB-SC', 'FM', 'GMSK', 'OQPSK']


<>:3: SyntaxWarning: invalid escape sequence '\A'
<>:3: SyntaxWarning: invalid escape sequence '\A'
C:\Users\asus\AppData\Local\Temp\ipykernel_4260\961659012.py:3: SyntaxWarning: invalid escape sequence '\A'
  with open("E:\AMC\datasets\RadioMl2018\classes-fixed.json", "r") as f:


In [70]:
label=Y[0]
print(label)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [63]:
class_index = np.argmax(label)
print(f"Class index: {class_index}")

Class index: 0


In [64]:
modulation_type = classes[class_index]
print(f"Modulation type: {modulation_type}")

Modulation type: OOK


## 6. Dataset Index Explorer

Each RadioML sample is identified by a single dataset index `i`.

For a given index:

- `X[i]` contains the 1024 × 2 I/Q samples.
- `Y[i]` contains the one-hot encoded modulation label.
- `Z[i]` contains the SNR value.

Therefore, each index can be represented as:

    i → (IQ signal, modulation, SNR)

The purpose of this section is to explore the relationship between dataset indices, modulation classes, and SNR values.

This will allow us to select specific samples such as:

- OOK at 10 dB
- BPSK at 0 dB
- QPSK at -10 dB
- AM-DSB-WC at 20 dB

In [65]:
# Load labels and SNR information

labels = np.argmax(Y[:], axis=1)
snrs = Z[:].reshape(-1)

print("Labels shape:", labels.shape)
print("SNR shape:", snrs.shape)

Labels shape: (2555904,)
SNR shape: (2555904,)


In [66]:
for i, modulation in enumerate(classes):
    print(f"{i:2d} : {modulation}")

 0 : OOK
 1 : 4ASK
 2 : 8ASK
 3 : BPSK
 4 : QPSK
 5 : 8PSK
 6 : 16PSK
 7 : 32PSK
 8 : 16APSK
 9 : 32APSK
10 : 64APSK
11 : 128APSK
12 : 16QAM
13 : 32QAM
14 : 64QAM
15 : 128QAM
16 : 256QAM
17 : AM-SSB-WC
18 : AM-SSB-SC
19 : AM-DSB-WC
20 : AM-DSB-SC
21 : FM
22 : GMSK
23 : OQPSK


In [67]:
unique_snrs = np.unique(snrs)

print("Available SNR values:")
print(unique_snrs)

Available SNR values:
[-20 -18 -16 -14 -12 -10  -8  -6  -4  -2   0   2   4   6   8  10  12  14
  16  18  20  22  24  26  28  30]


In [68]:
print("Number of SNR levels:", len(unique_snrs))

Number of SNR levels: 26


In [69]:
print("Samples per modulation")
print("-" * 35)

for class_index, modulation in enumerate(classes):

    count = np.sum(labels == class_index)

    print(f"{modulation:12s} : {count}")

Samples per modulation
-----------------------------------
OOK          : 106496
4ASK         : 106496
8ASK         : 106496
BPSK         : 106496
QPSK         : 106496
8PSK         : 106496
16PSK        : 106496
32PSK        : 106496
16APSK       : 106496
32APSK       : 106496
64APSK       : 106496
128APSK      : 106496
16QAM        : 106496
32QAM        : 106496
64QAM        : 106496
128QAM       : 106496
256QAM       : 106496
AM-SSB-WC    : 106496
AM-SSB-SC    : 106496
AM-DSB-WC    : 106496
AM-DSB-SC    : 106496
FM           : 106496
GMSK         : 106496
OQPSK        : 106496


In [ ]:
import pandas as pd
'''this code snippet is used to create a distribution table of modulation types across different SNR values. It uses the pandas library to create a crosstab,
 which shows the count of samples for each modulation type at each SNR level. The resulting distribution table can be useful for analyzing the dataset and 
 understanding how different modulation types are represented across various SNR conditions.'''

modulation_names = np.array(classes)[labels]

distribution = pd.crosstab(
    modulation_names,
    snrs
)

distribution

col_0,-20,-18,-16,-14,-12,-10,-8,-6,-4,-2,...,12,14,16,18,20,22,24,26,28,30
row_0,,,,,,,,,,,,,,,,,,,,,
128APSK,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
128QAM,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
16APSK,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
16PSK,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
16QAM,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
256QAM,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
32APSK,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
32PSK,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096
32QAM,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096,...,4096,4096,4096,4096,4096,4096,4096,4096,4096,4096


In [ ]:
'''this function returns the indices of samples that match a specific modulation type and SNR value. 
It takes two parameters: modulation (the desired modulation type) and snr (the desired SNR value). 
The function first finds the index of the specified modulation type in the classes list. 
Then, it uses NumPy's where function to find the indices of samples that have both the specified modulation type and SNR value. 
Finally, it returns the array of matching indices.
'''
def get_indices(modulation, snr):
    
    class_index = classes.index(modulation)

    indices = np.where(
        (labels == class_index) &
        (snrs == snr)
    )[0]

    return indices

In [ ]:
'''this code snippet demonstrates how to use the get_indices function to retrieve the indices of 
samples that match a specific modulation type and SNR value.'''

'''for example, it retrieves the indices of samples with modulation type "OOK" and SNR value 10.
The resulting indices are then printed, along with the total number of samples found, the first 10 indices, 
and the last 10 indices. This allows for a quick inspection of the samples that meet the specified criteria.'''

indices_ook = get_indices("OOK", 10)    

print("Number of samples:", len(indices_ook))
print("First 10 indices:", indices_ook[:10])
print("Last 10 indices:",indices_ook[-10:])

Number of samples: 4096
First 10 indices: [61440 61441 61442 61443 61444 61445 61446 61447 61448 61449]
Last 10 indices: [65526 65527 65528 65529 65530 65531 65532 65533 65534 65535]


In [ ]:
indices_ook = get_indices("OOK", 10)

print(indices_ook)

[61440 61441 61442 ... 65533 65534 65535]


In [84]:
indices_fm = get_indices("FM", 16)
print("Number of samples:", len(indices_fm))
print("First 10 indices:", indices_fm[:10])
print("Last 10 indices:",indices_fm[-10:])

Number of samples: 4096
First 10 indices: [2310144 2310145 2310146 2310147 2310148 2310149 2310150 2310151 2310152
 2310153]
Last 10 indices: [2314230 2314231 2314232 2314233 2314234 2314235 2314236 2314237 2314238
 2314239]


In [85]:
sample_index=indices_fm[1000]

In [90]:
print("Dataset index:", sample_index)

Encoded_Label=Y[sample_index]
Decoded_Label=classes[np.argmax(Y[sample_index])]
SNR=Z[sample_index]

print("Encoded label:", Encoded_Label)
print("Decoded label:", Decoded_Label)

print("SNR:", SNR)

Dataset index: 2311144
Encoded label: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
Decoded label: FM
SNR: [16]


In [93]:
'''Connecting the Index back to X
'''
iq = X[sample_index]

print(f"IQ samples for index no. {sample_index} of {Decoded_Label} modulation at SNR:{SNR} is:\n ")
print("IQ shape:", iq.shape)
print("First 5 IQ samples:")
print(iq[:5])

IQ samples for index no. 2311144 of FM modulation at SNR:[16] is:
 
IQ shape: (1024, 2)
First 5 IQ samples:
[[-0.36360645  0.93342865]
 [-0.59736603  0.8612023 ]
 [-0.8144014   0.735345  ]
 [-0.9445977   0.5820171 ]
 [-1.0296812   0.37001705]]


In [ ]:
'''this function selects a sample index based on the specified modulation type and SNR value. 
It takes three parameters: modulation (the desired modulation type), snr (the desired SNR value ),  
and random (a boolean indicating whether to select a random sample or the first one).'''

def select_sample(modulation, snr, random=False, seed=42):

    indices = get_indices(modulation, snr)

    if len(indices) == 0:
        raise ValueError(
            f"No samples found for {modulation} at {snr} dB."
        )

    if random:
        rng = np.random.default_rng(seed)
        index = rng.choice(indices)
    else:
        index = indices[0]

    return index

In [96]:
sample_index = select_sample(
    modulation="OOK",
    snr=10,
    random=True
)

print("Selected index:", sample_index)



Selected index: 61805


In [101]:
'''this function inspects a sample from the dataset based on the specified modulation type and SNR value.
It takes four parameters: modulation (the desired modulation type), snr (the desired SNR value),
random (a boolean indicating whether to select a random sample or the first one), and seed (the random 
seed for reproducibility).'''

def inspect_sample(modulation, snr, random=False, seed=42):

    index = select_sample(
        modulation,
        snr,
        random=True,
        seed=seed
    )

    iq = X[index]

    actual_label = classes[np.argmax(Y[index])]
    actual_snr = Z[index].item()

    print("Sample Information")
    print("-" * 35)
    print(f"Index      : {index}")
    print(f"Modulation : {actual_label}")
    print(f"SNR        : {actual_snr} dB")
    print(f"IQ Shape   : {iq.shape}")

    return index, iq

In [102]:
index, iq = inspect_sample("OOK", 10)

Sample Information
-----------------------------------
Index      : 61805
Modulation : OOK
SNR        : 10 dB
IQ Shape   : (1024, 2)


In [99]:
index, iq = inspect_sample("AM-DSB-WC", 20)

Sample Information
-----------------------------------
Index      : 2105344
Modulation : AM-DSB-WC
SNR        : 20 dB
IQ Shape   : (1024, 2)


In [ ]:
def get_first_last_indices(labels, snrs, classes):
    """
    Return the first and last dataset index for every
    modulation type at every SNR level.
    here, labels-> array of label indices
    snrs-> array of SNR values
    classes-> list of modulation types
    """

    result = {}

    for class_index, modulation in enumerate(classes):

        result[modulation] = {}

        for snr in np.unique(snrs):

            indices = np.where(
                (labels == class_index) &
                (snrs == snr)
            )[0]

            if len(indices) > 0:
                result[modulation][snr] = {
                    "first": indices[0],
                    "last": indices[-1],
                    "count": len(indices)
                }

    return result

In [104]:
index_ranges = get_first_last_indices(
    labels,
    snrs,
    classes
)

In [105]:
for modulation in classes:

    print(f"\n{modulation}")
    print("-" * 35)

    for snr in sorted(index_ranges[modulation]):

        data = index_ranges[modulation][snr]

        print(
            f"{snr:>4} dB : "
            f"{data['first']} → {data['last']} "
            f"({data['count']} samples)"
        )


OOK
-----------------------------------
 -20 dB : 0 → 4095 (4096 samples)
 -18 dB : 4096 → 8191 (4096 samples)
 -16 dB : 8192 → 12287 (4096 samples)
 -14 dB : 12288 → 16383 (4096 samples)
 -12 dB : 16384 → 20479 (4096 samples)
 -10 dB : 20480 → 24575 (4096 samples)
  -8 dB : 24576 → 28671 (4096 samples)
  -6 dB : 28672 → 32767 (4096 samples)
  -4 dB : 32768 → 36863 (4096 samples)
  -2 dB : 36864 → 40959 (4096 samples)
   0 dB : 40960 → 45055 (4096 samples)
   2 dB : 45056 → 49151 (4096 samples)
   4 dB : 49152 → 53247 (4096 samples)
   6 dB : 53248 → 57343 (4096 samples)
   8 dB : 57344 → 61439 (4096 samples)
  10 dB : 61440 → 65535 (4096 samples)
  12 dB : 65536 → 69631 (4096 samples)
  14 dB : 69632 → 73727 (4096 samples)
  16 dB : 73728 → 77823 (4096 samples)
  18 dB : 77824 → 81919 (4096 samples)
  20 dB : 81920 → 86015 (4096 samples)
  22 dB : 86016 → 90111 (4096 samples)
  24 dB : 90112 → 94207 (4096 samples)
  26 dB : 94208 → 98303 (4096 samples)
  28 dB : 98304 → 102399 (4096 

In [106]:
def get_index_range(modulation, snr):
    """
    Return the first and last dataset indices for
    a given modulation and SNR.
    """

    if modulation not in index_ranges:
        raise ValueError(f"Unknown modulation: {modulation}")

    if snr not in index_ranges[modulation]:
        raise ValueError(
            f"No data found for {modulation} at {snr} dB"
        )

    first = index_ranges[modulation][snr]["first"]
    last = index_ranges[modulation][snr]["last"]

    return first, last

In [107]:
first, last = get_index_range("OOK", 10)

print("First index:", first)
print("Last index :", last)

First index: 61440
Last index : 65535
